name: trends
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^3.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  intl: ^0.16.1
  http: ^0.12.1
  pull_to_refresh: ^1.5.8
  rxdart: ^0.24.1
  shared_preferences: ^0.5.7+3
  provider: ^4.1.3
  moor_ffi: 0.5.0
  path_provider:
  path:
  audioplayers: ^0.15.1
  share: ^0.6.4+3
  firebase_messaging: ^6.0.16
  dio: ^3.0.9
  firebase_remote_config: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.2.0
  build_runner:
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/NoInternet.png
    - assets/images/Splash.png

    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

  fonts:
    - family: NewspaperIcon
      fonts:
        - asset: assets/icons/NewspaperIcon.ttf
    - family: MoonIcon
      fonts:
        - asset: assets/icons/MoonIcon.ttf
    - family: HeartIcon
      fonts:
        - asset: assets/icons/Heart.ttf
    - family: Shuffle
      fonts:
        - asset: assets/icons/Shuffle.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
