/// Flutter icons NewspaperIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewspaperIcon
///      fonts:
///       - asset: fonts/NewspaperIcon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'NewspaperIcon';
  static const _kFontPkg = null;

  static const _kFontFam1 = 'MoonIcon';
  static const _kFontPkg1 = null;

  static const IconData newspaper =
      IconData(0xf1ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xe808, fontFamily: _kFontFam1, fontPackage: _kFontPkg1);
}
